# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Website
email: bwallad@gmail.com
description: I will be using this as I place to share my personal thoughts and projects

#baseurl: "/blog" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mrbino
github_username:  wallawaz

# Build settings
markdown: kramdown
